In [ ]:
import collections
import copy
import numpy as np
import json
import os
import matplotlib
import matplotlib.pyplot as plt
from scipy import signal
from scipy.ndimage import measurements
import skimage.exposure
from sklearn import linear_model
from typing import Any, Dict, Iterable, List, Mapping, Optional, Tuple

In [ ]:
import gdal
import gdalconst

In [ ]:
 pip install git+https://github.com/ulikoehler/UliEngineering.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/ulikoehler/UliEngineering.git to /tmp/pip-req-build-1dd1w4tn
  Running command git clone -q https://github.com/ulikoehler/UliEngineering.git /tmp/pip-req-build-1dd1w4tn


In [ ]:
from UliEngineering.Math.Coordinates import BoundingBox

In [ ]:
from google.colab import drive # m.p. added cell, this cell mounts your google drive to the colab
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [ ]:
#from json import JSONEncoder


In [ ]:
import pandas as pd


In [ ]:
"""
class bounding_box_encoder (JSONEncoder):
  def default(self, o):
      return o._dict_
"""

In [ ]:
directory1 = '/content/gdrive/MyDrive/json_image_files/filenames_with_contrails'
for filename in os.listdir(directory1):
  print(filename)
  
  f= open(os.path.join(directory1,filename))
  indiv_json_file = json.loads(f.read()) # reads file in as a python object
  polygon_list = indiv_json_file['polygons'] # list of polygons
  outer_list_counter = 0 # set counter to Zero, this will be the 1st index of the outer list
  inner_list_counter = 0 # set counter to Zero, this will be the 1st index of the inner list
  num_of_contrails_in_scene = len(polygon_list) # count the range of the outer for loop
  num_of_points_along_contrail = len(polygon_list[outer_list_counter]) # count the range for the inner for loop
  current_contrail = polygon_list[outer_list_counter] # list of current contrail
  points_along_contrail_list = polygon_list[outer_list_counter][inner_list_counter] # list of [x,y] coordinates of current contrail

  for contrail in range (len(polygon_list)): # start to loop through the contrails
    print(len(polygon_list))
    print(len(polygon_list[outer_list_counter]))
    x_y_coordinates = np.asarray(polygon_list[outer_list_counter]) # convert to numpy array
    print(x_y_coordinates)
    bbox= BoundingBox(x_y_coordinates)
    print(bbox)
    print(type(bbox)) # this is not serializable
    print(type(bbox.minx)) # this is a numpy array float

    # Must convert bounding box to a serializable python object
    x_1 = bbox.minx
    x_2 = bbox.maxx
    y_1 = bbox.miny
    y_2 = bbox.maxy

    # conversions to regular float
    min_x = x_1.item() 
    max_x = x_2.item()
    min_y = y_1.item()
    max_y = y_2.item()

    #Verify type conversion
    #print(type(min_x)) 
    #print(type(max_x))

    # create list to hold bounding box coordinates
    bounding_box_list = [ min_x,max_x, min_y,max_y] # create list to hold bbox coordinates
    print(bounding_box_list)
    polygon_list[outer_list_counter].append(bounding_box_list)    # add bbox as dictionary
    outer_list_counter = outer_list_counter + 1

  directory2 = '/content/gdrive/MyDrive/json_image_files/json_files_with_bbox_data'
  path = os.path.join(directory2,filename)
  with_bbox_file = open(path, "w")
  indiv_json_file = json.dumps(indiv_json_file, indent= 2 )# converts back to json file
  with_bbox_file.write(indiv_json_file)

#with_bbox_file.close()  


  


Streaming output truncated to the last 5000 lines.
BoundingBox(382.9, 471.83, 330.92, 353.87)
<class 'UliEngineering.Math.Coordinates.BoundingBox'>
<class 'numpy.float64'>
[382.9, 471.83, 330.92, 353.87]
32
9
[[450.02 316.86]
 [449.71 312.91]
 [421.76 306.83]
 [386.82 302.88]
 [350.05 297.72]
 [332.74 301.97]
 [333.95 305.01]
 [353.7  302.27]
 [409.3  309.56]]
BoundingBox(332.74, 450.02, 297.72, 316.86)
<class 'UliEngineering.Math.Coordinates.BoundingBox'>
<class 'numpy.float64'>
[332.74, 450.02, 297.72, 316.86]
32
5
[[699.63 201.54]
 [701.3  199.87]
 [671.04 191.06]
 [670.8  193.92]
 [682.48 196.54]]
BoundingBox(670.8, 701.3, 191.06, 201.54)
<class 'UliEngineering.Math.Coordinates.BoundingBox'>
<class 'numpy.float64'>
[670.8, 701.3, 191.06, 201.54]
LC08_L1TP_033040_20180417_20180501_01_T1_B10.json
2
6
[[611.39 736.39]
 [578.61 763.96]
 [568.18 770.66]
 [568.18 776.62]
 [604.69 747.56]
 [611.39 740.86]]
BoundingBox(568.18, 611.39, 736.39, 776.62)
<class 'UliEngineering.Math.Coordinates

In [ ]:
print(x_y_coordinates[0])
print(type(x_y_coordinates[0]))
print(x_y_coordinates.shape)
print(type(indiv_json_file))

[601.79 185.61]
<class 'numpy.ndarray'>
(4, 2)
<class 'dict'>


In [ ]:
print(bbox)

BoundingBox(599.32, 624.49, 170.75, 185.61)
